### PR TITLE
feat: Add coderadio meta image

### PR DESCRIPTION
**Pull request by nhcarrigan**
Signed-off-by: Nicholas Carrigan <nhcarrigan@gmail.com>

Per discussion with @ahmadabdolsaheb - this PR adds a specific meta image for our code radio platform. Once this is approved/deployed, I'll PR an update to the client repo to use this image over our default meta image.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by ojeytonwilliams** [comment]
Seems to be fine: https://5fd391fc32e4450007b1ca76--freecodecamp-cdn.netlify.app/platform/universal/fcc_meta_1920x1080-coderadio.png

I guess we can just merge this and Netlify will do the rest, but unless this is urgent, I'm in favour of waiting until we don't have to guess!

**Comment by nhcarrigan** [comment]
Definitely not urgent. Right now the meta image for coderadio is our standard indigo logo. This should be fine to leave until we are confident in merging 🙂

**Comment by ojeytonwilliams** [comment]
Cool.  I'm 99% sure this is safe, but if it's not urgent, let's not rush.

**Comment by ahmadabdolsaheb** [comment]
Thanks for taking care of this feature. I think we could change the name and the location so it follows a new convention that we are adapting to standardize assets across platforms.

We have not finalized the platform specific assets yet. What do you think of platform-description-size?

Should it be build/coderadio/coderadio-meta-1920x1080.png?
cc @scissorsneedfoodtoo

This seems to be a large file, just curious where you found it since the background image on coderadio is ≈250kb.

**Comment by nhcarrigan** [comment]
> Should it be build/coderadio/coderadio-meta-1920x1080.png?

Sure, I can move it there. 🙂 

> This seems to be a large file, just curious where you found it since the background image on coderadio is ≈250kb.

This was a screenshot pulled from the live app.

**Comment by ojeytonwilliams** [comment]
Belatedly, I realised I wasn't sure what this was for.  Is it for Facebook? If so, I found some [guidelines](https://developers.facebook.com/docs/sharing/webmasters/images/) and apparently they want 1200 by 630, so we should probably stick to that ratio.  Here's an example screenshot that's a little larger than that (but has the same aspect ratio) that might be useful.

Coderadio

**Comment by nhcarrigan** [comment]
This is for the Open Graph image, which is what both Facebook and Discord use (others too, I'm sure, but that's what I can think of off hand). I was going with the 1920x1080 size to mirror our existing indigo meta image - if we want to use a smaller size, then the default meta image should probably be replaced as well. 🤔

**Comment by ojeytonwilliams** [comment]
I couldn't find a canonical guide, but a bit of searching turned up: https://iamturns.com/open-graph-image-size/#cheatsheet which suggests that 1200x630 is the best, but that it probably doesn't matter a great deal.

If we're targeting Facebook, that's probably the way to go.  If we have another platform in mind, maybe not.

**Comment by scissorsneedfoodtoo** [comment]
Hey @nhcarrigan, thanks for adding this image. Also, thanks for offering to move it to `build/coderadio/coderadio-meta...` -- that seems to be a good path for this.

I ran the image @ojeytonwilliams through TinyPNG, then through Kraken.io. Kraken offers a bit more customization, and at 50% quality was able to get the image down to about 416 kB:

101990231-11743c00-3ca6-11eb-90c2-75b05cc6957a-2

Still pretty big, but a bit better than before.

Also, I notice that expressions on both images are slightly different. I don't have a real preference -- either would make great meta images.

**Comment by nhcarrigan** [comment]
Okay, I've moved the file to the new location and replaced the image with the resized version from @scissorsneedfoodtoo's comment.

**Comment by ahmadabdolsaheb** [comment]
Thank you @nhcarrigan :)

**Pull request merged**
