### PR TITLE
chore: add trending file and dayjs locale for Indonesian

### PR DESCRIPTION
**Pull request by RafaelDavisH**
- chore: create yaml file for indonesian
- Chore: add minified dayjs file for Indonesian

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi Rafa. I only see English in the minified file. Isn't this supposed to be localised?

**Comment by ojeytonwilliams** [comment]
I assume https://github.com/iamkun/dayjs/blob/dev/src/locale/id.js is what we want.

**Comment by RafaelDavisH** [comment]
> I assume https://github.com/iamkun/dayjs/blob/dev/src/locale/id.js is what we want.

If this is what we are asking, I think we should state that clearly in the 'docs for News launches:

https://github.com/freeCodeCamp/freeCodeCamp/pull/48025/files#diff-5ff127d888351d31f0355c34a5c4a6685878f8d6fb798f367f7e21404d59c761R321

Can someone confirm if this PR should be updated to what @ojeytonwilliams pointed out or not, Pls?

**Comment by scissorsneedfoodtoo** [comment]
Hey @RafaelDavisH, sorry if the docs were unclear. I can update them now so they're more specific.

We have the main dayjs files we need, but those only include English as a locale by default.

To add a new locale like Indonesian, we need to add this fine to the CDN: https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.10.4/locale/id.min.js

**Comment by scissorsneedfoodtoo** [comment]
Everything LGTM.

The `indonesian.yaml` file for trending articles and links was added in an earlier PR, but it should be okay to overwrite the current file with the one here.

Also, thank you for adding the minified Indonesian DayJS locale.

I'll merge this now and do another round of testing with your changes in https://github.com/freeCodeCamp/news/pull/470.

**Review by scissorsneedfoodtoo — APPROVED** [review]

**Pull request merged**
