### PR TITLE
fix: change advertisement images to cat photos

### PR DESCRIPTION
**Pull request by staranbeer**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/46640

### CODE REVIEW

**Comment by lasjorg** [comment]
Not sure if we are using these or not.

Where did you get the images from? Are they from unsplash? We need to make sure they are licensed in a way that allows for their usage.

If we do use them, I think I'd like to scale them down to half the resolution to make them smaller in size. But you may want to wait until we know if are using these or not.

**Comment by staranbeer** [comment]
> Not sure if we are using these or not.
> 
> Where did you get the images from? Are they from unsplash? We need to make sure they are licensed in a way that allows for their usage.
> 
> If we do use them, I think I'd like to scale them down to half the resolution to make them smaller in size. But you may want to wait until we know if are using these or not.

i downloaded them from pexels and just to be sure i read their license agreement and all of the photos on the site are free for personal and commercial use.

image

**Comment by ShaunSHamilton** [comment]
> image
> 
> Is this correct? These images are absolutely massive.

Yes, but that is why I compressed them all to under `300kB`

**Comment by staranbeer** [comment]
> Thank you for taking the time to contribute to this, @staranbeer
> 
> I have pushed a commit with our desired changes.
> 
> All images used have Creative Commons 0 licenses, and I have compressed them to ~275kB

sure! let me know if i can help in any other way!

**Review by nhcarrigan — APPROVED** [review]
Let's go with it.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Efficient

**Comment by lasjorg** [comment]
I created a new PR with smaller images and one image removed.

**Comment by ShaunSHamilton** [comment]
@staranbeer Thank you for taking the time to contribute.

We have gone with another solution to this. So, I am going to close this PR.

Feel free to find an open issue with the `help wanted` label, and contribute to that 🙂

**Pull request closed without merging**
