### PR TITLE
fix: kebab case file names

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Renames all PDF files to use kebab case as mention in https://github.com/freeCodeCamp/freeCodeCamp/issues/41913

Note: I went with strict lower case for all words (including for abbreviations/acronyms).

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by lasjorg** [comment]
@raisedadead That was fast, thank you.

**Comment by raisedadead** [comment]
Nope. Thank you for making these changes! Let me know if this fixes your local setup.

**Comment by RandellDawson** [comment]
Shouldn't it be `build/youtube/cobol-course/additional-information-1.pdf` instead of `build/youtube/cobol-course/additional-Information-1.pdf`?

**Comment by lasjorg** [comment]
@RandellDawson I guess I missed that. I can make a new PR to fix it.

@raisedadead I just tested it and it did fix the issue.

**Comment by lasjorg** [comment]
PR https://github.com/freeCodeCamp/cdn/pull/67

**Pull request merged**
