### PR TITLE
cdn(image): add react logo and license

### PR DESCRIPTION
**Pull request by lasjorg**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

For use in the Markdown Previewer example project.

I put this in its own folder and included the license. Not sure if anything else is needed?

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
This makes sense to me. Although, I am not sure what happens to the license on the CDN.

**Comment by lasjorg** [comment]
> I am not sure what happens to the license on the CDN.

What do you mean?

**Comment by ShaunSHamilton** [comment]
> > I am not sure what happens to the license on the CDN.
> 
> What do you mean?

Just odd to upload and host another license on the CDN, is all.

**Comment by ojeytonwilliams** [comment]
Based on Section three of https://github.com/reactjs/reactjs.org/blob/master/LICENSE-DOCS.md, I think we need to supply the license 'with' the licensed material. I think, in this context, 'with' would mean that we should include a link as part of the logo itself.

**Comment by lasjorg** [comment]
@ojeytonwilliams You mean when using the logo in the project we have to add a link to the license? We can do that.

We can also just use the fCC logo instead and forget about using the React logo. Maybe that's an easier/safer choice?

**Comment by ojeytonwilliams** [comment]
Yeah, I think that makes sense.  The point is to show *an* image - I don't think there any need for it to be the React logo.

**Comment by lasjorg** [comment]
I will close this and use the fCC logo.

@ojeytonwilliams I'm not sure if I should copy the logo into the `/testable-projects-fcc` folder on the CDN or just use the one in `/platform/universal`.

I'm leaning towards copying it so we know the path/name won't change and break the link.  It's also where all the other example project images are located.

**Comment by ojeytonwilliams** [comment]
@lasjorg sure, a copy for this project makes perfect sense.

**Pull request closed without merging**
