### PR TITLE
fix: image extensions

### PR DESCRIPTION
**Pull request by nhcarrigan**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

Need these to be .jpg, not .png.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Aren't they actually PNGs, though?

**Comment by nhcarrigan** [comment]
I converted them.

Or, I thought I did 🤔 

Lemme try again.

**Comment by ojeytonwilliams** [comment]
To be perfectly honest, I didn't check in a very sophisticated way: I just opened one up in an editor and it said 'PNG'.

**Review by ojeytonwilliams — COMMENTED** [review]
And now it says JFIF and they're smaller, so I think it's worked :+1:

**Pull request merged**
