### PR TITLE
feat: add trending YAML files for each locale

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to https://github.com/freeCodeCamp/news/issues/219

This is in preparation to start working on a PR to source the trending titles and links from a single source.

Just let me know if there's a better place to put these files, or a better way to structure the directories. We could also use the ISO language code instead if that's easier.

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

The file structure seems reasonable and we can always tweak it if there's a better one.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reviewing this @ojeytonwilliams.

I just reviewed and merged #122.

Now that the YAML linting action is in, should we test it with this PR?

**Comment by ojeytonwilliams** [comment]
@scissorsneedfoodtoo it's looking good.  I confirmed that it'll catch anything inside `build` when I was setting up the other PR, so I think we're good.

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Thanks again for your help getting these in.

**Pull request merged**
