### PR TITLE
feat: add data files for machine learning projects

### PR DESCRIPTION
**Pull request by beaucarnes**
These files are used in the new machine learning challenges. The challenges require students to import the data or images and analyze the data in different ways.

### CODE REVIEW

**Comment by raisedadead** [comment]
Quick confirmation

`build/project-data/insurance.csv` should this be `build/project-data/<some name>/insurance.csv` like other csv files?

**Comment by beaucarnes** [comment]
@raisedadead I was not planning to put that in its own directory since only one file is required for that project. The directory was used since there were multiple files required for the project. If you think it would be better, I could make a directory for each project.

**Comment by raisedadead** [comment]
I would recommend that (folder per project) actually to avoid confusion in future.

**Comment by beaucarnes** [comment]
OK, I made folders for each project and renamed some files.

**Comment by raisedadead** [comment]
Great, these changes should be available within a few minutes on the CDN.

**Pull request merged**
