### PR TITLE
Convert signature image into SVG

### PR DESCRIPTION
**Pull request by caglarturali**
I've converted the signature image into SVG. This PR should be merged after #20

### CODE REVIEW

**Comment by caglarturali** [comment]
@tbushman Could you merge this one also? SVG is a more viable option than PNG.

**Comment by saranshkataria** [comment]
@caglarturali should I remove the png then?

**Comment by caglarturali** [comment]
> @caglarturali should I remove the png then?

I think it will stay there until someone notices that it hasn't been used anywhere in the codebase. :) So, just make sure you're using SVG version when updating the website repo.

**Comment by saranshkataria** [comment]
In my opinion, Since it is a fresh start and references to the CDN are to be added beginning now onwards, it makes sense to remove the png and only have the SVG.

**Comment by caglarturali** [comment]
@saranshkataria Agreed, but apparently, the team is busy nowadays and it could take some time the PR to be merged that you'd open to remove the png. But you are always free to do so.

By the way, @tbushman, we were told that the assets in the repo will be made available at `https://cdn.freecodecamp.org/[ASSET_PATH]` but it hasn't been done yet. Could you take a look at this?

**Comment by saranshkataria** [comment]
Have created #22 removing the png. Whenever someone gets time, they can merge it. But waiting for the assets to be available at the CDN URL to fix the signature issue

**Pull request merged**
