### PR TITLE
feat: add pictures for exercise D - The Odin Project

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@Sembauke could you let us know where these are sourced from? Mostly so we can be sure there's no need for attribution.

**Comment by Sembauke** [comment]
they are sourced from here https://github.com/TheOdinProject/css-exercises/tree/main/foundations/04-chaining-selectors
@ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
Thanks, unfortunately the issue is it's not clear how (or if) we can get the rights to use these. Maybe reach out to the photographers if you can't find the photos on the web?

**Comment by Sembauke** [comment]
Hey @ojeytonwilliams,

./pexels-katho-mutodo-8434791.jpg
./pexels-andrea-piacquadio-3777931.jpg

The images are from Pexels not Getty Images
https://www.pexels.com/ - it is a free image website

**Comment by naomi-lgbt** [comment]
From their ToS:

> 5.7. Be aware that, depending on your intended use of the Content, you may need the permission or consent of a third party (e.g. owner of a brand, identifiable person or author/rights holder of copyrightable work depicted in the Content).

Not sure if these people count as identifiable, but are these specific images necessary? Could we replace them with something more generic?

**Comment by Sembauke** [comment]
Yes we could use some of our images, already present in the CDN.

**Review by ojeytonwilliams — APPROVED** [review]
They look familiar!

LGTM :+1:

**Pull request merged**
