### PR TITLE
Update math-code-test-a.py

### PR DESCRIPTION
**Pull request by edatfreecodecamp**
I fixed the typo in step 21 and the tab issue in line 258. Thank you for catching those. This should be good now (really this time)

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

I fixed the typo in step 21 and the tab issue in line 258. Thanks

### CODE REVIEW

**Comment by scissorsneedfoodtoo** [comment]
Hey Ed, hope you don't mind, but I pushed a couple of fixes directly to your new branch here. I found another typo, and some semicolons that I missed in my last review. There were also some minor linting warnings I saw, so I let the Python VS Code extension I have fix those as well.

Other than that, everything looks fine :+1: :+1: 

I'm not sure what the best way to test this is. I threw the updated file into Replit and tried to run most of the functions. Some were missing variables (`numerator`, `In`, and so on), but I'm guessing that those will be added by learners as they go through the steps.

After adding some dummy variables on Replit, those functions seem to run fine. This should be okay to merge since it's still in active development, but just wanted to give a heads up to the next reviewer.

**Comment by edatfreecodecamp** [comment]
Kris,
Thank you. I tried to run this and I got an error that line 258 has a tab (instead of spaces). I thought I had fixed this. I use spaces for indenting. Would you be able to edit that line? Thanks again. I appreciate your time
-Ed

**Comment by scissorsneedfoodtoo** [comment]
Hey @edatfreecodecamp, I  took another look and wasn't able to find any tabs on line 258, or elsewhere throughout the file. That may have been fixed by the linter I ran the code through earlier.

You might need to pull down the latest version of the file. There are a few ways to do that, but the easiest way to get the latest code is to go to the [raw version of the file](https://raw.githubusercontent.com/freeCodeCamp/cdn/71c83ad664468820a1bf92d7db5b0a7b82da7693/build/math-cert-tests/math-code-test-a.py), copy the code, and paste it into an editor.

Could you try that and let me know if you're still getting the same error message about the tab on that line?

**Comment by edatfreecodecamp** [comment]
Yes! That was it. Thanks, Kris. I was still linking to another version of the file. I just tested it and it works. We are ready to share the link now

**Pull request merged**
