### PR TITLE
adding data folder with choropleth map counties.json file

### PR DESCRIPTION
**Pull request by tbushman**
We can consider moving other files here...

### CODE REVIEW

**Comment by tbushman** [comment]
@raisedadead Do you think these folders are ok?

**Comment by raisedadead** [comment]
Thanks @tbushman the file should be available at https://cdn.freecodecamp.org/testable-projects-fcc/data/choropleth_map/counties.json

**Comment by tbushman** [comment]
@raisedadead Thanks! Now I'm seeing that the user stories direct students to @no-stack-dub-sack 's repo: 
screen shot 2018-06-28 at 11 01 25 pm
...so the file doesn't seem to be in use from the testable-projects repo. :/ I think I should add the other dataset as well and hopefully redirect students here instead.

**Comment by raisedadead** [comment]
I see can you create a issue with the correct URLs on the curriculum repo for all such links?

For example, the final links will be:
`https://cdn.freecodecamp.org/testable-projects-fcc/data/choropleth_map/counties.json`

The `build` directory on this repo becomes the root

**Comment by tbushman** [comment]
@raisedadead Thanks, yes. :)

**Pull request merged**
