### PR TITLE
feat: The Odin Project pictures

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Before merging, need to confirm that all of the instructional text content in these images is mirrored in the challenge texts for i18n purposes.

**Comment by Sembauke** [comment]
Now how would we link the images for the different locales?

**Comment by naomi-lgbt** [comment]
The images themselves can stay as they are, but the text content in the challenge needs to reflect all of the information in the image. For example, for this li'l guy I might include the following text in the challenge:

image


> In the above image, the `padding` text points to the padding of the element, the `border` text points to the border of the element, and the `margin` text points to the margin of the element.

**Comment by Sembauke** [comment]
But what has that to do with these images? I still have no clue what you're trying to explain.

**Comment by naomi-lgbt** [comment]
> We can reflect on the description of these images in the main repo.

Yes, that is what I am asking. I want to make sure that is either already done, or in the works, so that it doesn't get forgotten about and become an i18n nightmare later. :3

**Comment by Sembauke** [comment]
I was planning on doing this when updating the URLs 🙃

**Review by naomi-lgbt — APPROVED** [review]

**Pull request merged**
