### PR TITLE
feat: add moment.js for news

### PR DESCRIPTION
**Pull request by scissorsneedfoodtoo**
This adds Moment.js for date localization on /news.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Can we maybe use something other than moment?  It's just that the project maintainers [recommend avoiding it](https://momentjs.com/docs/#/-project-status/).

It would be great if we could use, say, date-fns, bundle everything up and let Webpack include only the packages we actually need. However, if it's tricky to integrate libraries with Ghost, don't worry about it

**Comment by ojeytonwilliams** [comment]
Thinking about it: if you've already written stuff with moment, let's go with that - it's not worth tearing up code for a relatively small gain, imo.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, sure, I can take a crack at using date-fns or something similar. Moment is recommended in the Ghost docs, but that was probably some time ago. The main thing it's used for is just some internationalization and formatting, so it might be pretty easy to swap it out for date-fns.

**Comment by ojeytonwilliams** [comment]
Cool. If we can't bundle it the gains are pretty minor, so I'd go with whichever seems cleanest.

**Comment by scissorsneedfoodtoo** [comment]
Closing in favor of https://github.com/freeCodeCamp/cdn/pull/59.

**Pull request closed without merging**
