### PR TITLE
feat: add image for learn variables and operators The Odin Project

### PR DESCRIPTION
**Pull request by Sembauke**
Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Does this image need attribution or is this something you created?

**Comment by Sembauke** [comment]
What do you mean by "attribution" ?

**Comment by Sembauke** [comment]
I am not sure, it is used in The Odin Project. But I don't think that's enough of a reason:
https://www.theodinproject.com/lessons/foundations-variables-and-operators

cc @raisedadead

**Comment by raisedadead** [comment]
Its a CC-BY-SA-4.0, https://www.theodinproject.com/terms_of_use - you will need to add an attribution to the odin project (where the images is) as a caption, and mention that its a CC-BY-SA-4.0 

OR

Figure out not needing to the images.

**Comment by Sembauke** [comment]
image
Is this not enough? It's approved by The Odin team themselves. Adding anything to the image itself is absolute overkill.

**Comment by raisedadead** [comment]
> Is this not enough? 

That is perfect.

**Pull request merged**
