### PR TITLE
feat: add binary search tree asset

### PR DESCRIPTION
**Pull request by zairahira**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Adding the asset for step-1 in the "Binary Search Tree" Python curriculum project.

### CODE REVIEW

**Review by ShaunSHamilton — CHANGES_REQUESTED** [review]
I would prefer we not name the folder `upcoming-python`. Maybe just `python`. At the end of the day, there is nothing specific to Python about this image.

Also, could someone confirm if we have a build step to reduce file size? Otherwise, we cannot go with a 77KB image.

**Comment by zairahira** [comment]
> I would prefer we not name the folder `upcoming-python`. Maybe just `python`. At the end of the day, there is nothing specific to Python about this image.
> 
> Also, could someone confirm if we have a build step to reduce file size? Otherwise, we cannot go with a 77KB image.

What's the recommended size?

**Comment by ojeytonwilliams** [comment]
@ShaunSHamilton yep, https://github.com/freeCodeCamp/cdn/pull/218 is an example of it at work.

Also, it should be cached, so learners will only have to download it once.

**Comment by ShaunSHamilton** [comment]
> What's the recommended size?

As low as possible to still use the image. The one Quincy liked as an example is 1KB.

**Comment by ojeytonwilliams** [comment]
There are a few online image compression tools we can play with. https://tinypng.com/ seems okay, quality-wise, and got it down to 23.8kb.

Or we can just let the bot do it's thing and see how much it can save.

**Comment by zairahira** [comment]
I have compressed the image to 16KB.

**Comment by ojeytonwilliams** [comment]
That's much better - they look identical to me. Nice work, Zaira.

**Review by naomi-lgbt — CHANGES_REQUESTED** [review]
Ideally, instructional images should not contain text. Otherwise we can't translate the content.

Can we confirm that the instructions will identify, in text, all of the information conveyed here?

Also, the `upcoming-python` directory still needs to be removed.

**Comment by zairahira** [comment]
Yes @naomi-lgbt, the instructions would cover the details mentioned in the image.

**Review by naomi-lgbt — APPROVED** [review]

**Review by ShaunSHamilton — APPROVED** [review]
Thank you.

**Pull request merged**
